-- +goose Up
CREATE TYPE skill_level AS ENUM(
  'beginner',
  'intermediate',
  'advanced'
);

CREATE TABLE IF NOT EXISTS personalization_options(
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "account_id" INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  "roadmap_id" INTEGER NOT NULL REFERENCES roadmaps(id) ON DELETE CASCADE,
  "daily_time_availability" INTERVAL NOT NULL,
  "total_duration" INTERVAL NOT NULL,
  "skill_level" skill_level NOT NULL,
  "additional_info" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now())
);

-- +goose Down
DROP TABLE IF EXISTS personalization_options;

DROP TYPE IF EXISTS skill_level;
