-- +goose Up
CREATE TYPE skill_level AS ENUM(
  'beginner',
  'intermediate',
  'advanced'
);

CREATE TABLE IF NOT EXISTS personalization_options(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INTEGER,
  roadmap_id INTEGER,
  daily_time_availability INTERVAL NOT NULL,
  total_duration INTERVAL NOT NULL,
  skill_level skill_level NOT NULL,
  additional_info TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT personalization_options_fk_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
  CONSTRAINT personalization_options_fk_roadmap FOREIGN KEY (roadmap_id) REFERENCES roadmaps(id) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE IF EXISTS personalization_options;

DROP TYPE IF EXISTS skill_level;
