-- +goose Up
CREATE TABLE IF NOT EXISTS roadmaps(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INTEGER NOT NULL,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT roadmaps_fk_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS topics(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INTEGER NOT NULL,
  roadmap_id INTEGER NOT NULL,
  parent_id INTEGER,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  "order" INTEGER NOT NULL,
  finished BOOLEAN NOT NULL DEFAULT FALSE,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT (now()),
  CONSTRAINT topics_fk FOREIGN KEY (roadmap_id) REFERENCES roadmaps(id) ON DELETE CASCADE,
  CONSTRAINT topics_fk_parent FOREIGN KEY (parent_id) REFERENCES topics(id) ON DELETE CASCADE
);

CREATE INDEX idx_roadmaps_slug ON roadmaps(slug);

CREATE INDEX idx_topics_slug ON topics(slug);

-- +goose Down
DROP TABLE IF EXISTS topics;

DROP TABLE IF EXISTS roadmaps;
